name: Release
on: [release]
jobs:
    pipeline:
        name: supportivecare pipeline
        runs-on: ubuntu-latest
        if: github.event.action == 'published'
        timeout-minutes: 40
        env:
            NODE_VERSION: 14.15.0
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.15.0
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Install node.js packages
              run: npm install
            - name: Package application
              run: |
                  chmod +x mvnw
                  npm run java:jar:prod
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: artifact
                path: target/*.jar
                retention-days: 2
                if-no-files-found: error
            - name: Deploy to Heroku PROD
              env:
                HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
              run: |
                if [ ! -z "$HEROKU_API_KEY" ]; then
                    ./mvnw -ntp com.heroku.sdk:heroku-maven-plugin:2.0.5:deploy -DskipTests -Pprod -Dheroku.buildpacks=heroku/jvm -Dheroku.appName=supportivecare
                else
                    echo No HEROKU_API_KEY, skipping...
                fi
