name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: supportivecare pipeline
        runs-on: ubuntu-latest
        timeout-minutes: 40
        env:
            NODE_VERSION: 14.15.4
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.15.4
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Install node.js packages
              run: npm install
            - name: Run backend test
              run: |
                  chmod +x mvnw
                  npm run ci:backend:test
            - name: Run frontend test
              run: npm run ci:frontend:test
            - name: Analyze code with SonarQube
              if: (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
                  (github.event_name == 'pull_request')
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  if [ ! -z "$SONAR_TOKEN" ]; then
                      ./mvnw -ntp initialize sonar:sonar -Dsonar.organization=mse-2019-2021 -Dsonar.host.url=https://sonarcloud.io
                  else
                      echo No SONAR_TOKEN, skipping...
                  fi
            - name: Package application
              run: npm run java:jar:prod
            - name: Upload artifact
              if: github.event_name == 'push' && github.ref == 'refs/heads/master'
              uses: actions/upload-artifact@v2
              with:
                name: artifact
                path: target/*.jar
                retention-days: 2
                if-no-files-found: error
            - name: Deploy to Heroku QA
              if: github.event_name == 'push' && github.ref == 'refs/heads/master'
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
              run: |
                  if [ ! -z "$HEROKU_API_KEY" ]; then
                      ./mvnw -ntp com.heroku.sdk:heroku-maven-plugin:2.0.5:deploy -DskipTests -Pprod -Dheroku.buildpacks=heroku/jvm -Dheroku.appName=supportivecare-qa -Deureka.instance.hostname=supportivecare-qa.herokuapp.com
                  else
                      echo No HEROKU_API_KEY, skipping...
                  fi
            - name: 'E2E: Package'
              run: npm run ci:e2e:package
            - name: 'E2E: Prepare'
              run: npm run ci:e2e:prepare
            - name: 'E2E: Run'
              run: npm run ci:e2e:run
            - name: 'E2E: Teardown'
              run: npm run ci:e2e:teardown
